version: "3.9"

services:
  webdev:
    image: node:alpine
    user: node
    working_dir: /var/www/app
    environment:
      - HOST=0.0.0.0
    ports:
      - 3083:3000
    volumes:
      - .:/var/www/app
    command: ["/bin/sh", "-c", "npm install && npm run dev"]
