name: super-run-ci-cd

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build-code:
    runs-on: ubuntu-latest
    steps:

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 15.6

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: make lint

      - name: Retrieve variables from Terraform
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: make .env && cat .env

      - name: Unit test
        run: echo npm run test - todo!

      - name: Generate static project
        run: npm run generate

      - name: Upload build artifact to Github Actions
        uses: actions/upload-artifact@v2
        with:
          name: frontend-dist-${{ github.sha }}
          path: ./dist
          if-no-files-found: error
          retention-days: 7

  cd:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: build-code
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        id: download
        uses: actions/download-artifact@v2
        with:
          name: frontend-dist-${{ github.sha }}
          path: ./dist

      - name: File structure
        run: ls -R

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./dist

  smoke:
    needs: cd
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 15.6

      - name: Install dependencies
        run: npm install

      - name: File structure
        working-directory: ~
        run: ls -R

      - name: Smoke test
        working-directory: ~
        run: make smoke
