name: super-run-ci

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint code
        run: echo todo !!!
      - name: Retrieve API conneciton URL
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: make lambda-url
      - name: Unit test
        run: echo todo!!!
